apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      name: nginx-apache-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-ct
          image: nginx:alpine
          ports:
          - containerPort: 80
        - name: nodejs-ct
          image: khannedy/nodejs-web
          ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nginx
  ports:
    - port: 81
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: ryan.local
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80
          - path: /nodejs
            backend:
              serviceName: nodejs-service
              servicePort: 81
          