apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: pod-nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-ct
          image: nginx
          ports:
            - containerPort: 80